ServerRoot "/usr/local/apache2"
Listen 80
ServerName webdav
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule dav_module modules/mod_dav.so
LoadModule dav_fs_module modules/mod_dav_fs.so
LoadModule log_config_module modules/mod_log_config.so
User daemon
Group daemon
ErrorLog /proc/self/fd/2
LogLevel warn
DocumentRoot "/data"
DavLockDB "/usr/local/apache2/var/DavLock"
<Directory "/">
  AllowOverride None
  Require all denied
</Directory>
<Directory "/data">
  Dav On
  AuthType Basic
  AuthName "Oh My Tab Backup"
  AuthUserFile "/auth/users"
  Require valid-user
  LimitRequestBody 67108864
</Directory>
